language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"

cache: pip

install:
  - "sudo apt-get update -q"
  - "sudo apt-get install -y python3-lxml libenchant-dev"
  - "pip install -r ./travis/requirements.txt"

script:
  - "py.test . -R : -v --cov . --cov-report term-missing --pylint --pylint-rcfile=travis/pylintrc"

after_success:
  - "coveralls"

env:
  - PYTHONPATH=.
  - PYTHONPATH=. PYTHONASYNCIODEBUG=1

matrix:
  allow_failures:
    - python: "nightly"
  include:
    - python: '3.7'
      dist: xenial
      sudo: true
    - python: '3.8-dev'
      dist: xenial
      sudo: true

